name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        cd fasthtml
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fasthtml:$GITHUB_SHA .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fasthtml:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_RUN_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fasthtml:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated